[package]
name = "ai-agent-tool-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["visit", "extra-traits"] }
quote = "1.0"
ai-agent-tool = { path = "../ai-agent-tool" }
